version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - backend_keys:/app/keys

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - backend

volumes:
  backend_logs:
  backend_keys: 